-- Script para postgres
CREATE TABLE IF NOT EXISTS CLIENTE(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    PRECO NUMERIC(20, 2)
);

CREATE TABLE IF NOT EXISTS PEDIDO(
    ID SERIAL PRIMARY KEY,
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20, 2)
);

CREATE TABLE IF NOT EXISTS ITEM_PEDIDO(
    ID SERIAL PRIMARY KEY,
    PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
    QUANTIDADE INTEGER
);